### ISSUE TITLE
Unable to parse copybook with Redefines clause

### ISSUE THREAD

**Issue by Shalini174** [zalmane/copybook#3]
Hi,

I am trying to use the package, but i am getting below error for REDEFINES clause. Please help.

Traceback (most recent call last):
  File "C:\Users\PycharmProjects\pythonProject\venv\copybook_sample.py", line 2, in <module>
    root = copybook.parse_file('POLICY.txt')
  File "C:\Users\PycharmProjects\pythonProject\venv\lib\site-packages\copybook\copybook.py", line 10, in parse_file
    result:FieldGroup = stmt.parseFile(filename,parseAll=True)
  File "C:\Users\PycharmProjects\pythonProject\venv\lib\site-packages\pyparsing\core.py", line 1899, in parse_file
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '05'  (at char 215), (line:6, col:14)

Process finished with exit code 1

copybook:

         01 POLICY.
             05 POLICY-KEY         PIC 9(10).
	     05 ROW-EFFECTIVE-DT   PIC X(8).
	     05 POLICY-BINDING-DT  PIC X(8).
	     05 POLICY-HOLDER-KEY  PIC 9(10).
	     05 PRODUCT-KEY REDEFINES POLICY-HOLDER-KEY PIC X(10).

**Comment by zalmane** [comment]
Fixed. It did not support REDEFINE for single field. I added support so should be OK now. Please check (and 'star' if works for you).

**Comment by Shalini174** [comment]
Hi,

Thank you for the help. It is now working fine for me. However, for OCCURS also, i am getting same error - 

C:\Users\shalini.f.gupta\PycharmProjects\pythonProject\venv\Scripts\python.exe C:/Users/shalini.f.gupta/PycharmProjects/pythonProject/venv/copybook_sample.py
Traceback (most recent call last):
  File "C:\Users\PycharmProjects\pythonProject\venv\copybook_sample.py", line 2, in <module>
    root = copybook.parse_file('POLICY_OCCURS.txt')
  File "C:\Users\PycharmProjects\pythonProject\venv\lib\site-packages\copybook\copybook.py", line 10, in parse_file
    result:FieldGroup = stmt.parseFile(filename,parseAll=True)
  File "C:\Users\PycharmProjects\pythonProject\venv\lib\site-packages\pyparsing\core.py", line 1899, in parse_file
    raise exc.with_traceback(None)
pyparsing.exceptions.ParseException: Expected end of text, found '05'  (at char 79), (line:3, col:14)


COPYBOOK :

         01 POLICY.
             05 POLICY-KEY         PIC 9(10).
	     05 ROW-EFFECTIVE-DT   OCCURS 4 TIMES PIC 9(8).

Is there a format that we need to follow?

**Comment by zalmane** [comment]
I'll add support. Originally it only handled OCCURS and REDEFINES for
groups. Seems your copybook has these set up for individual fields.

**Comment by Shalini174** [comment]
Hi, 
Thank you for the help. Please let me know once the above is fixed.

**Comment by zalmane** [comment]
done

**Comment by Shalini174** [comment]
Thank you. It is working fine for me now.
